export const demoUser = {
  name: 'Demo User',
  email: 'demo@example.com',
  password: '12345678',
};

export const demoTasks = [
  {
    title: 'Fix authentication bug',
    description: 'Resolve token expiration issue.',
    priority: 9,
    category: 'Work',
    isCompleted: false,
    isPrivate: false,
    dueDate: new Date('2026-07-26'),
  },
  {
    title: 'Book dentist appointment',
    description: 'Schedule a regular check-up.',
    priority: 6,
    category: 'Personal',
    isCompleted: false,
    isPrivate: true,
    dueDate: new Date('2026-07-23'),
  },
  {
    title: 'Buy birthday gift',
    description: 'Choose a present for a friend.',
    priority: 4,
    category: 'Shopping',
    isCompleted: false,
    isPrivate: false,
    dueDate: new Date('2026-07-24'),
  },
  {
    title: 'Prepare sprint report',
    description: 'Summarize completed tasks for the team.',
    priority: 8,
    category: 'Work',
    isCompleted: true,
    isPrivate: false,
    dueDate: new Date('2026-07-17'),
  },
  {
    title: 'Clean workspace',
    description: 'Organize desk and remove unnecessary items.',
    priority: 2,
    category: 'Personal',
    isCompleted: true,
    isPrivate: false,
    dueDate: new Date('2026-07-18'),
  },
  {
    title: 'Review pull requests',
    description: 'Check teammates’ code and leave feedback.',
    priority: 7,
    category: 'Work',
    isCompleted: false,
    isPrivate: false,
    dueDate: new Date('2026-07-22'),
  },
  {
    title: 'Pay utility bills',
    description: 'Electricity, water and internet.',
    priority: 8,
    category: 'Personal',
    isCompleted: false,
    isPrivate: true,
    dueDate: new Date('2026-07-21'),
  },
  {
    title: 'Weekly grocery shopping',
    description: 'Vegetables, fruit, meat and bread.',
    priority: 3,
    category: 'Shopping',
    isCompleted: true,
    isPrivate: false,
    dueDate: new Date('2026-07-19'),
  },
  {
    title: 'Plan weekend trip',
    description: 'Choose destination and book accommodation.',
    priority: 5,
    category: 'Personal',
    isCompleted: false,
    isPrivate: false,
    dueDate: new Date('2026-07-30'),
  },
  {
    title: 'Refactor task service',
    description: 'Improve readability and split large functions.',
    priority: 10,
    category: 'Work',
    isCompleted: false,
    isPrivate: false,
    dueDate: new Date('2026-07-29'),
  },
  {
    title: 'Finish Docker setup',
    description: 'Configure Docker Compose.',
    priority: 10,
    category: 'Work',
    isCompleted: false,
    isPrivate: false,
    dueDate: new Date('2026-07-25'),
  },
  {
    title: 'Buy groceries',
    description: 'Milk, eggs, cheese.',
    priority: 3,
    category: 'Shopping',
    isCompleted: false,
    isPrivate: false,
    dueDate: new Date('2026-07-20'),
  },
  {
    title: 'Workout',
    description: 'Leg day.',
    priority: 5,
    category: 'Personal',
    isCompleted: false,
    isPrivate: false,
    dueDate: new Date('2026-07-19'),
  },
  {
    title: 'Prepare portfolio',
    description: 'Update GitHub projects.',
    priority: 9,
    category: 'Work',
    isCompleted: false,
    isPrivate: false,
    dueDate: new Date('2026-07-27'),
  },
  {
    title: 'Read Clean Code',
    description: 'Read chapters 1-3.',
    priority: 4,
    category: 'Personal',
    isCompleted: true,
    isPrivate: false,
    dueDate: new Date('2026-07-18'),
  },
];
