const daysFromNow = (offset: number): Date => {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + offset);
  return date;
};

export const demoUsers = [
  {
    name: 'Demo User',
    email: 'demo@example.com',
    password: '12345678',
  },
  {
    name: 'Test User',
    email: 'test@example.com',
    password: '12345678',
  },
];
export const demoTasks = [
  {
    title: 'Fix authentication bug',
    description: 'Resolve token expiration issue on the login endpoint.',
    priority: 9,
    category: 'Work',
    isCompleted: false,
    isPrivate: false,
    dueDate: daysFromNow(-5),
  },
  {
    title: 'Renew car insurance',
    description: 'Policy expired last week, compare quotes before renewing.',
    priority: 7,
    category: 'Personal',
    isCompleted: false,
    isPrivate: true,
    dueDate: daysFromNow(-3),
  },
  {
    title: 'Submit tax documents',
    description: '',
    priority: 8,
    category: 'Todo',
    isCompleted: false,
    isPrivate: false,
    dueDate: daysFromNow(-1),
  },

  {
    title: 'Review pull requests',
    description: "Check teammates' code and leave feedback before standup.",
    priority: 7,
    category: 'Work',
    isCompleted: false,
    isPrivate: false,
    dueDate: daysFromNow(0),
  },
  {
    title: 'Pay utility bills',
    description: 'Electricity, water and internet.',
    priority: 8,
    category: 'Personal',
    isCompleted: false,
    isPrivate: true,
    dueDate: daysFromNow(0),
  },

  {
    title: 'Weekly grocery shopping',
    description: 'Vegetables, fruit, meat and bread for the week.',
    priority: 3,
    category: 'Shopping',
    isCompleted: false,
    isPrivate: false,
    dueDate: daysFromNow(1),
  },
  {
    title: 'Book dentist appointment',
    description: 'Schedule a regular check-up.',
    priority: 6,
    category: 'Personal',
    isCompleted: false,
    isPrivate: true,
    dueDate: daysFromNow(2),
  },
  {
    title: 'Study React Server Components',
    description:
      'Go through the official docs and rebuild the demo app locally to understand streaming and suspense boundaries properly.',
    priority: 5,
    category: 'Study',
    isCompleted: false,
    isPrivate: false,
    dueDate: daysFromNow(3),
  },
  {
    title: 'Buy birthday gift',
    description: 'Choose a present for a friend.',
    priority: 4,
    category: 'Shopping',
    isCompleted: false,
    isPrivate: false,
    dueDate: daysFromNow(3),
  },

  {
    title: 'Morning run',
    description: '5km easy pace.',
    priority: 4,
    category: 'Health',
    isCompleted: false,
    isPrivate: false,
    dueDate: daysFromNow(5),
  },
  {
    title: 'Annual health check-up',
    description: 'Blood work and general check-up at the clinic.',
    priority: 6,
    category: 'Health',
    isCompleted: false,
    isPrivate: true,
    dueDate: daysFromNow(6),
  },

  {
    title: 'Plan weekend trip',
    description: 'Choose destination and book accommodation.',
    priority: 5,
    category: 'Personal',
    isCompleted: false,
    isPrivate: false,
    dueDate: daysFromNow(10),
  },
  {
    title: 'Refactor task service',
    description: 'Improve readability and split large functions.',
    priority: 10,
    category: 'Work',
    isCompleted: false,
    isPrivate: false,
    dueDate: daysFromNow(14),
  },
  {
    title: 'Prepare portfolio',
    description: 'Update GitHub projects and write short case studies.',
    priority: 9,
    category: 'Work',
    isCompleted: false,
    isPrivate: false,
    dueDate: daysFromNow(20),
  },

  {
    title: 'Read Clean Code',
    description: 'Whenever there is time — no rush.',
    priority: 2,
    category: 'Study',
    isCompleted: false,
    isPrivate: false,
  },
  {
    title: 'Organize digital photo library',
    description: '',
    priority: 1,
    category: 'Todo',
    isCompleted: false,
    isPrivate: false,
  },

  {
    title: 'Prepare sprint report',
    description: 'Summarize completed tasks for the team.',
    priority: 8,
    category: 'Work',
    isCompleted: true,
    isPrivate: false,
    dueDate: daysFromNow(-4),
  },
  {
    title: 'Clean workspace',
    description: 'Organize desk and remove unnecessary items.',
    priority: 2,
    category: 'Personal',
    isCompleted: true,
    isPrivate: false,
    dueDate: daysFromNow(-6),
  },
  {
    title: 'Finish Docker setup',
    description: 'Configure Docker Compose for local development.',
    priority: 10,
    category: 'Work',
    isCompleted: true,
    isPrivate: false,
    dueDate: daysFromNow(-2),
  },
  {
    title: 'Meal prep for the week',
    description: 'Cooked and portioned five lunches.',
    priority: 3,
    category: 'Health',
    isCompleted: true,
    isPrivate: false,
    dueDate: daysFromNow(-1),
  },
  {
    title: 'Buy groceries',
    description: 'Milk, eggs, cheese.',
    priority: 3,
    category: 'Shopping',
    isCompleted: true,
    isPrivate: false,
    dueDate: daysFromNow(-3),
  },
];
